name: Publish Docker Images

on:
  push:
    branches:
      - main  # Run only on pushes to main
    paths:
      - "cf-sf-apex-cache-builder"  # Trigger only if specific action folders change

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write  # Required for publishing to GitHub Packages
      contents: read

    strategy:
      matrix:
        action: [cf-sf-apex-cache-builder]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and tag Docker image
        run: |
          cd ${{ matrix.action }}
          docker build -t ghcr.io/${{ github.repository }}/${{ matrix.action }}:latest \
                       -t ghcr.io/${{ github.repository }}/${{ matrix.action }}:${{ github.sha }} .

      - name: Push Docker images
        run: |
          docker push ghcr.io/${{ github.repository }}/${{ matrix.action }}:latest
          docker push ghcr.io/${{ github.repository }}/${{ matrix.action }}:${{ github.sha }}
